# do not touch this line
configVersion: 2

description: Face Recognition for VISA hackaton
keywords: matrix faceID
name: fr
shortName: fr
displayName: Fr


events:
  - test
  - train
  - recog
  - reset
  - stopper
  
services:
  re:
    engine: recognition
    type: face

screens: 
  - - train
  - - recognize
  
widgets:
  train:
    event: train
    control: button
    label: 'Train your Face'
    value: 'Train'
  recognize:
    event: recog
    control: button
    label: Recognize Your Face
    value: Recognize
  
  
